packages:
  - "packages/*"

catalog:
  "@types/node": "^24.10.0"
  "@types/react": "^19.2.0"
  "@types/react-dom": "^19.2.0"
  "@vitejs/plugin-react": "^5.2.0"
  "clsx": "^2.1.1"
  "lucide-react": "^0.544.0"
  "react": "19.2.3"
  "react-dom": "19.2.3"
  "tailwind-merge": "^3.3.1"
  "tailwindcss": "^4.1.14"
  "typescript": "~6.0.3"
  "vitest": "^3.2.4"
  "zod": "^4.1.12"

overrides:
  "@ez4/aws-common": "file:./vendor/ez4-aws-common-0.52.0.tgz"
  "@ez4/raw-pg": "file:./vendor/ez4-raw-pg-0.52.0.tgz"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
