import { useEffect, useState } from "react";
import { Pressable, Share, Text, TextInput, View } from "react-native";
import type { AuthUser, AccountSession } from "@receivy/common";
import { ACCOUNT_DELETED, ACCOUNT_DELETION_UNCONFIRMED } from "@receivy/common";
import { accountClient, type AccountClient } from "@/account/client";
import { profileStore } from "@/account/profile";
import { LegalText } from "./legal-text";

export function AccountSettings({ client = accountClient }: { client?: AccountClient }) {
  const [user, setUser] = useState<AuthUser | null>(null); const [sessions, setSessions] = useState<AccountSession[]>([]); const [name, setName] = useState(""); const [timezone, setTimezone] = useState("America/Sao_Paulo"); const [confirmation, setConfirmation] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [ended, setEnded] = useState(false); const [legal, setLegal] = useState<"terms" | "privacy" | null>(null);
  useEffect(() => { let active = true; void Promise.all([client.profile(), client.sessions()]).then(([profile, devices]) => { if (active) { setUser(profile); setName(profile.name ?? ""); setTimezone(profile.timezone); setSessions(devices); } }, () => active && setNotice("Não foi possível carregar sua conta.")); return () => { active = false; }; }, [client]);
  async function save() { setBusy(true); try { const saved = await client.save({ name, locale: "pt-BR", country: "BR", timezone }); setUser(saved); profileStore.remember(saved); setNotice("Perfil salvo."); } catch { setNotice("Não foi possível salvar. Confira seu nome e fuso horário."); } finally { setBusy(false); } }
  async function revoke(item: AccountSession) { setBusy(true); try { await client.revoke(item.id); setSessions(rows => rows.filter(x => x.id !== item.id)); if (item.current) { await client.logout(); setEnded(true); setNotice("Sessão encerrada."); } } catch { setNotice("Não foi possível encerrar a sessão."); } finally { setBusy(false); } }
  async function exportData() { setBusy(true); try { const data = await client.export(); await Share.share({ title: data.filename, message: data.json }); setNotice("Exportação preparada. Compartilhe apenas com um destino seguro."); } catch { setNotice("Não foi possível exportar. Tente novamente."); } finally { setBusy(false); } }
  async function erase() { if (confirmation !== "EXCLUIR" || busy) return; setBusy(true); let confirmed = false; try { confirmed = await client.erase(); } catch {} setEnded(true); setNotice(confirmed ? ACCOUNT_DELETED : ACCOUNT_DELETION_UNCONFIRMED); setBusy(false); }
  const button = (label: string, action: () => void, disabled = false) => <Pressable accessibilityRole="button" accessibilityState={{ disabled: busy || disabled }} disabled={busy || disabled} className="my-2 min-h-12 justify-center rounded-xl bg-primary px-4 disabled:opacity-40" onPress={action}><Text className="font-bold text-white">{label}</Text></Pressable>;
  return <View className="gap-3 py-5"><Text className="text-2xl font-bold text-ink">Sua conta</Text>{!!notice && <Text accessibilityLiveRegion="polite" className="text-ink">{notice}</Text>}
    {!ended && user && <><Text className="font-bold text-ink">Nome</Text><TextInput accessibilityLabel="Nome" value={name} maxLength={120} onChangeText={setName} className="min-h-12 rounded-xl border border-line bg-white px-4" />
      <Text>Idioma: Português (Brasil). País: Brasil (MVP).</Text><Text className="font-bold">Fuso horário</Text><TextInput accessibilityLabel="Fuso horário" value={timezone} onChangeText={setTimezone} autoCapitalize="none" className="min-h-12 rounded-xl border border-line bg-white px-4" />{button("Salvar perfil", () => void save(), !name.trim())}
      <Text className="text-xl font-bold">Sessões e dispositivos</Text>{sessions.map(item => <View key={item.id}><Text>{item.deviceName}{item.current ? " (esta sessão)" : ""}</Text><Text>Último acesso: {new Date(item.lastSeenAt).toLocaleString("pt-BR")}</Text>{button(`Encerrar ${item.deviceName}`, () => void revoke(item))}</View>)}
        <Text>Exportação privada em JSON, autorizada por cinco minutos e protegida pela sessão ativa.</Text>{button("Exportar dados", () => void exportData())}
        <Text className="text-xl font-bold">Excluir conta</Text><Text>Encerra sessões, revoga links e remove seus arquivos identificados. Registros compartilhados e comprovantes de outras pessoas podem ser preservados com referências anonimizadas. Avisos já enviados não podem ser recolhidos.</Text><Text>Digite EXCLUIR para confirmar</Text><TextInput accessibilityLabel="Digite EXCLUIR para confirmar" value={confirmation} onChangeText={setConfirmation} autoCapitalize="characters" className="min-h-12 rounded-xl border border-line bg-white px-4" />{button("Excluir conta definitivamente", () => void erase(), confirmation !== "EXCLUIR")}
    </>}{button("Termos de uso", () => setLegal(legal === "terms" ? null : "terms"))}{button("Privacidade", () => setLegal(legal === "privacy" ? null : "privacy"))}{legal && <LegalText kind={legal} />}</View>;
}
