import { calendarDate, formatMoney, parseBRLCents, resolveExpenseSplit, type ExpenseInput, type PaymentMethod, type Person, type SplitMode } from "@receivy/common";
import * as Crypto from "expo-crypto";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { financialClient, type FinancialClient } from "@/financial/client";
import { peopleClient } from "@/people/client";

export function ChargeCreateScreen({ client = financialClient, people = peopleClient, onBack, onCreated }: { client?: Pick<FinancialClient, "paymentMethods" | "createExpense">; people?: Pick<typeof peopleClient, "list">; onBack?: () => void; onCreated?: (id: string) => void }) {
  const [contacts, setContacts] = useState<Person[]>([]); const [methods, setMethods] = useState<PaymentMethod[]>([]); const [selected, setSelected] = useState<string[]>([]); const [owner, setOwner] = useState(true);
  const [amount, setAmount] = useState(""); const [description, setDescription] = useState(""); const [count, setCount] = useState("1"); const [date, setDate] = useState(() => calendarDate()); const [methodId, setMethodId] = useState(""); const [mode, setMode] = useState<SplitMode>("equal"); const [values, setValues] = useState<Record<string, string>>({});
  const [review, setReview] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [uncertain, setUncertain] = useState(false); const [key] = useState(() => Crypto.randomUUID());
  useEffect(() => { void Promise.all([people.list(false).then(page => setContacts(page.people)), client.paymentMethods().then(page => { setMethods(page.paymentMethods); setMethodId(page.paymentMethods.find(item => item.isDefault)?.id ?? page.paymentMethods[0]?.id ?? ""); })]).catch(reason => setError(reason.message)); }, [client, people]);
  const plan = useMemo(() => { try { const totalCents = parseBRLCents(amount); const parties = [...selected.map(personId => ({ kind: "person" as const, personId })), ...(owner ? [{ kind: "owner" as const }] : [])]; const split = mode === "equal" ? { mode, parts: parties } as const : mode === "fixed" ? { mode, parts: selected.map(personId => ({ kind: "person" as const, personId, amountCents: parseBRLCents(values[personId] ?? "0") })) } as const : { mode, parts: parties.map(part => ({ ...part, basisPoints: Math.round(Number(values[part.kind === "owner" ? "owner" : part.personId] ?? 0) * 100) })) } as const; return { totalCents, split, allocations: resolveExpenseSplit(totalCents, Number(count), split) }; } catch { return null; } }, [amount, count, mode, owner, selected, values]);
  function prepare() { setError(""); if (!selected.length) return setError("Selecione ao menos um contato."); if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !plan) return setError("Confira valor, vencimento, parcelas e rateio."); setReview(true); }
  async function create() { if (!plan) return; setBusy(true); setError(""); setUncertain(false); const input: ExpenseInput = { description: description.trim() || undefined, totalCents: plan.totalCents, installmentCount: Number(count), firstDueDate: date, split: plan.split, paymentMethodId: methodId || undefined }; try { const result = await client.createExpense(input, key); const id = result.charges[0]?.id; if (!id) throw new Error("O detalhe da cobrança não foi retornado."); onCreated?.(id); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível criar a cobrança."); setUncertain(true); } finally { setBusy(false); } }
  const field = "min-h-12 rounded-xl border border-outline bg-canvas px-3 text-ink";
  return <SafeAreaView className="flex-1 bg-canvas"><ScrollView keyboardShouldPersistTaps="handled" contentContainerClassName="gap-5 px-5 pb-14 pt-2"><Pressable accessibilityRole="button" onPress={onBack} className="min-h-12 justify-center"><Text className="font-bold text-primary">← Timeline</Text></Pressable><Text className="text-4xl font-extrabold leading-10 text-primary-strong">Divida com clareza antes de cobrar.</Text><Text className="leading-6 text-muted">Seu rascunho permanece se a rede falhar.</Text>
    <View className="gap-3 rounded-3xl border border-outline bg-surface p-5"><Text className="text-xl font-bold text-primary-strong">1. Pessoas</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerClassName="gap-2">{contacts.map(person => <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: selected.includes(person.id) }} accessibilityLabel={person.name} onPress={() => setSelected(old => old.includes(person.id) ? old.filter(id => id !== person.id) : [...old, person.id])} key={person.id} className={`min-h-12 flex-row items-center gap-2 rounded-2xl border px-3 ${selected.includes(person.id) ? "border-primary bg-primary-soft" : "border-outline"}`}><View className="h-8 w-8 items-center justify-center rounded-xl bg-primary-soft"><Text className="font-bold text-primary-strong">{person.name[0]}</Text></View><Text className="font-semibold text-ink">{person.name}</Text></Pressable>)}</ScrollView><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: owner }} onPress={() => setOwner(value => !value)} className="min-h-12 justify-center"><Text className="font-semibold text-primary">{owner ? "☑" : "☐"} Incluir minha parte</Text></Pressable></View>
    <View className="gap-3 rounded-3xl border border-outline bg-surface p-5"><Text className="text-xl font-bold text-primary-strong">2. Valor</Text><Text className="font-semibold text-ink">Valor total</Text><TextInput accessibilityLabel="Valor total" inputMode="decimal" placeholder="0,00" value={amount} onChangeText={value => { setAmount(value); setReview(false); }} className={field} /><Text className="font-semibold text-ink">Descrição (opcional)</Text><TextInput accessibilityLabel="Descrição" maxLength={500} value={description} onChangeText={setDescription} className={field} /></View>
    <View className="gap-3 rounded-3xl border border-outline bg-surface p-5"><Text className="text-xl font-bold text-primary-strong">3. Parcelas e rateio</Text><TextInput accessibilityLabel="Quantidade de parcelas" keyboardType="number-pad" value={count} onChangeText={setCount} className={field} /><View className="flex-row flex-wrap gap-2">{[["equal", "Iguais"], ["fixed", "Fixos"], ["percentage", "Percentuais"]].map(([value, label]) => <Pressable accessibilityRole="button" key={value} onPress={() => setMode(value as SplitMode)} className={`min-h-12 justify-center rounded-full border px-4 ${mode === value ? "border-primary bg-primary-soft" : "border-outline"}`}><Text className="font-bold text-primary-strong">{label}</Text></Pressable>)}</View>{mode !== "equal" && [...selected.map(id => ({ id, label: contacts.find(person => person.id === id)?.name ?? id })), ...(mode === "percentage" && owner ? [{ id: "owner", label: "Minha parte" }] : [])].map(part => <View key={part.id}><Text className="mb-1 text-sm text-muted">{mode === "fixed" ? "Valor" : "Percentual"} de {part.label}</Text><TextInput accessibilityLabel={`${mode === "fixed" ? "Valor" : "Percentual"} de ${part.label}`} inputMode="decimal" value={values[part.id] ?? ""} onChangeText={value => setValues(old => ({ ...old, [part.id]: value }))} className={field} /></View>)}</View>
    <View className="gap-3 rounded-3xl border border-outline bg-surface p-5"><Text className="text-xl font-bold text-primary-strong">4. Vencimento e Pix</Text><TextInput accessibilityLabel="Primeiro vencimento" placeholder="AAAA-MM-DD" value={date} onChangeText={setDate} className={field} /><Text className="text-sm text-muted">Chave Pix usada nos links</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerClassName="gap-2"><Pressable onPress={() => setMethodId("")} className={`min-h-12 justify-center rounded-full border px-4 ${!methodId ? "bg-primary-soft" : "border-outline"}`}><Text>Sem chave</Text></Pressable>{methods.map(method => <Pressable key={method.id} onPress={() => setMethodId(method.id)} className={`min-h-12 justify-center rounded-full border px-4 ${methodId === method.id ? "bg-primary-soft" : "border-outline"}`}><Text>{method.label || method.pixKey}</Text></Pressable>)}</ScrollView></View>
    <Pressable accessibilityRole="button" accessibilityLabel="Revisar cobrança" onPress={prepare} className="min-h-14 items-center justify-center rounded-2xl bg-primary"><Text className="font-bold text-white">Revisar cobrança</Text></Pressable>{review && plan && <View className="gap-3 rounded-3xl border border-primary bg-surface p-5"><Text className="text-xl font-bold text-primary-strong">Revisão exata</Text><Text className="text-3xl font-extrabold text-ink">{formatMoney({ amountCents: plan.totalCents, currency: "BRL" })}</Text>{plan.allocations.map(item => <View key={item.kind === "owner" ? "owner" : item.personId} className="border-b border-outline py-2"><Text className="font-bold text-ink">{item.kind === "owner" ? "Minha parte" : contacts.find(person => person.id === item.personId)?.name}: {formatMoney({ amountCents: item.amountCents, currency: "BRL" })}</Text><Text className="text-xs text-muted">{item.installments.length}x</Text></View>)}<Pressable accessibilityRole="button" accessibilityLabel="Criar cobrança" disabled={busy} onPress={() => void create()} className="min-h-14 items-center justify-center rounded-2xl bg-primary">{busy ? <ActivityIndicator color="white" /> : <Text className="font-bold text-white">Criar cobrança</Text>}</Pressable></View>}{error ? <Text accessibilityRole="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</Text> : null}{uncertain && <Pressable accessibilityRole="button" accessibilityLabel="Tentar criar novamente" disabled={busy} onPress={() => void create()} className="min-h-12 items-center justify-center rounded-xl border border-outline"><Text className="font-bold text-primary">Tentar criar novamente</Text></Pressable>}
  </ScrollView></SafeAreaView>;
}
