import { formatMoney, type ChargeDetail } from "@receivy/common";
import * as Clipboard from "expo-clipboard";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, Share, Text, View } from "react-native";
import { SafeAreaView } from "@/components/safe-area-view";
import { financialClient, type FinancialClient } from "@/financial/client";
import { ProofPanel, type ProofClient } from "./proof-panel";
import { FirstSharePix } from "./first-share-pix";
import { NotificationPanel } from "./notification-panel";

export function ChargeDetailScreen({ id, client = financialClient }: { id: string; client?: Pick<FinancialClient, "charge" | "cancel" | "pay" | "publicLink" | "publicChargeUrl"> & Partial<ProofClient & Pick<FinancialClient, "paymentMethods" | "savePaymentMethod">> }) {
  const [charge, setCharge] = useState<ChargeDetail | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void client.charge(id).then(setCharge).catch(reason => setError(reason instanceof Error ? reason.message : "Não foi possível carregar a cobrança.")); }, [client, id]);
  async function copy(value: string, success: string) { try { await Clipboard.setStringAsync(value); setNotice(success); setError(""); } catch { setError("Não foi possível copiar agora."); } }
  async function transition(kind: "pay" | "cancel") { setBusy(true); setError(""); try { setCharge(await (kind === "pay" ? client.pay(id) : client.cancel(id))); setNotice(kind === "pay" ? "Pagamento integral registrado." : "Cobrança cancelada e mantida no histórico."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível atualizar a cobrança."); } finally { setBusy(false); } }
  async function shareLink(rotate = false, paymentMethodId?: string) { setBusy(true); setError(""); try { const result = await client.publicLink(id, rotate, paymentMethodId); if (paymentMethodId) setCharge(await client.charge(id)); const url = client.publicChargeUrl(result.token); await Share.share({ title: "Cobrança Receivy", message: url, url }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível compartilhar o link."); } finally { setBusy(false); } }
  return <SafeAreaView className="flex-1 bg-canvas" edges={["bottom"]}><ScrollView contentContainerClassName="gap-5 px-5 pb-12 pt-2">{!charge && !error && <ActivityIndicator accessibilityLabel="Carregando cobrança" color="#0B513D" />}{charge && <>
    <View className="gap-3"><Text className={`self-start rounded-full px-3 py-2 text-xs font-bold ${charge.direction === "receivable" ? "bg-primary-soft text-primary-strong" : "bg-violet-100 text-violet-900"}`}>{charge.direction === "receivable" ? "A receber" : "A pagar"}</Text><Text className="text-4xl font-extrabold tracking-tight text-primary-strong">{charge.description}</Text><Text className="text-muted">{charge.recipient.name} · vence em {new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(`${charge.dueDate}T00:00:00Z`))}</Text></View>
    <View className="gap-2 rounded-3xl border border-outline bg-surface p-6"><Text className="text-sm text-muted">Valor</Text><Text className="text-4xl font-extrabold text-ink">{formatMoney(charge.amount)}</Text><Text className="font-bold text-primary">{charge.state === "pending" ? "Pendente" : charge.state === "paid" ? "Pago" : "Cancelado"}</Text></View>
    {charge.pix && <View className="gap-3 rounded-3xl border border-outline bg-surface p-5"><Text className="text-xl font-bold text-primary-strong">Pagamento por Pix</Text><Text className="leading-6 text-muted">{charge.state === "pending" ? "Confira o nome do destinatário no seu banco antes de transferir." : "Chave Pix registrada no histórico desta cobrança."}</Text><Text selectable className="rounded-xl bg-surface-muted p-4 text-ink">{charge.pix.key}</Text><Pressable accessibilityRole="button" accessibilityLabel="Copiar chave Pix" onPress={() => void copy(charge.pix!.key, "Chave Pix copiada.")} className="min-h-12 items-center justify-center rounded-xl border border-outline"><Text className="font-bold text-primary">Copiar chave Pix</Text></Pressable></View>}
    {charge.direction === "receivable" && charge.state === "pending" ? <View className="gap-3 rounded-3xl border border-outline bg-surface p-5"><Text className="text-xl font-bold text-primary-strong">Ações</Text><Pressable accessibilityRole="button" accessibilityLabel="Marcar como paga" disabled={busy} onPress={() => Alert.alert("Marcar como paga?", "Isso registra um pagamento integral e encerra a cobrança.", [{ text: "Voltar", style: "cancel" }, { text: "Marcar paga", onPress: () => void transition("pay") }])} className="min-h-12 items-center justify-center rounded-xl bg-primary"><Text className="font-bold text-white">Marcar como paga</Text></Pressable>{charge.pix && <><Pressable accessibilityRole="button" accessibilityLabel="Compartilhar cobrança" disabled={busy} onPress={() => void shareLink()} className="min-h-12 items-center justify-center rounded-xl border border-outline"><Text className="font-bold text-primary">Compartilhar cobrança</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Trocar e compartilhar link" disabled={busy} onPress={() => void shareLink(true)} className="min-h-12 items-center justify-center rounded-xl border border-outline"><Text className="font-bold text-primary">Trocar e compartilhar link</Text></Pressable></>}<Pressable accessibilityRole="button" accessibilityLabel="Cancelar cobrança" disabled={busy} onPress={() => Alert.alert("Cancelar cobrança?", "Ela não aceitará pagamento e continuará no histórico.", [{ text: "Voltar", style: "cancel" }, { text: "Cancelar cobrança", style: "destructive", onPress: () => void transition("cancel") }])} className="min-h-12 items-center justify-center"><Text className="font-bold text-red-700">Cancelar cobrança</Text></Pressable></View> : <View className="rounded-2xl bg-surface-muted p-5"><Text className="leading-6 text-muted">{charge.direction === "payable" ? charge.state === "pending" ? charge.pix ? "Esta cobrança é somente leitura. Pague usando a chave Pix acima." : "A chave Pix ainda não está disponível. Combine o pagamento com o credor." : charge.state === "paid" ? "Esta cobrança já foi paga. Nenhuma nova transferência é necessária." : "Esta cobrança foi cancelada e não deve ser paga." : "Esta cobrança não aceita novas ações."}</Text></View>}
    {charge.direction === "receivable" && charge.sharingState === "pix_required" && client.paymentMethods && client.savePaymentMethod && <FirstSharePix client={client as FinancialClient} busy={busy} publish={methodId => shareLink(false, methodId)} />}
    {charge.sharingState === "legacy_without_pix" && <Text>Esta cobrança foi publicada sem Pix. O histórico não pode ser alterado nem receber um novo link; combine o pagamento manualmente com o credor.</Text>}
    {client.proofs && <ProofPanel charge={charge} client={client as ProofClient} onChanged={() => { void client.charge(id).then(setCharge).catch(() => setError("Atualize a cobrança para conferir a situação.")); }} />}
    <NotificationPanel id={id} canRemind={charge.direction === "receivable" && charge.state === "pending" && !!charge.pix} />
  </>}{error ? <Text accessibilityRole="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</Text> : null}{notice ? <Text accessibilityRole="alert" className="rounded-xl bg-primary-soft p-4 text-primary-strong">{notice}</Text> : null}</ScrollView></SafeAreaView>;
}
