import { useState } from "react";
import { Alert, Pressable, Text, TextInput, View } from "react-native";
import { normalizePerson, type Person } from "@receivy/common";
import { peopleClient } from "@/people/client";

export function PersonDetails({ person, changed, onNewCharge }: { person: Person; changed: () => Promise<void>; onNewCharge?: () => void }) {
  const [name, setName] = useState(person.name), [email, setEmail] = useState(person.email ?? ""), [phone, setPhone] = useState(person.phone ?? "");
  const [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  async function save(archive = false) { setBusy(true); setMessage(""); try { if (archive) await peopleClient.archive(person.id); else await peopleClient.save(normalizePerson({ name, email, phone }), person.id); await changed(); setMessage(archive ? "Contato arquivado; histórico preservado." : "Contato atualizado; cobranças antigas não foram alteradas."); } catch (error) { setMessage(error instanceof Error ? error.message : "Confira os dados."); } finally { setBusy(false); } }
  const field = "min-h-12 rounded-xl border border-outline px-3";
  return <View className="gap-3 rounded-3xl border border-outline bg-surface p-5"><Text className="text-2xl font-bold text-primary-strong">{person.name}</Text><Text>{person.hasAccount ? "Com conta" : "Sem conta"}{person.archivedAt ? " · Arquivado" : ""}</Text><TextInput accessibilityLabel="Nome" value={name} maxLength={120} editable={!person.archivedAt} onChangeText={setName} className={field} /><TextInput accessibilityLabel="E-mail" value={email} maxLength={254} editable={!person.archivedAt} autoCapitalize="none" onChangeText={setEmail} className={field} /><TextInput accessibilityLabel="Telefone" value={phone} maxLength={40} editable={!person.archivedAt} onChangeText={setPhone} className={field} />{!person.archivedAt && <><Pressable accessibilityRole="button" disabled={busy} onPress={() => void save()} className="min-h-12 justify-center"><Text className="font-bold text-primary">Salvar contato</Text></Pressable><Pressable accessibilityRole="button" disabled={busy} onPress={() => Alert.alert("Arquivar contato?", "O histórico será preservado.", [{ text: "Voltar", style: "cancel" }, { text: "Arquivar", onPress: () => void save(true) }])} className="min-h-12 justify-center"><Text>Arquivar contato</Text></Pressable><Pressable accessibilityRole="button" onPress={onNewCharge} className="min-h-12 justify-center"><Text className="font-bold text-primary">Nova cobrança</Text></Pressable></>}{message ? <Text accessibilityRole="alert">{message}</Text> : null}</View>;
}
