import { calendarDate, formatMoney, normalizeRecurrenceInput, parseBRLCents, parsePercentageBasisPoints, resolveExpenseSplit, type RecurrenceDetail, type RecurrenceInput, type Person, type PaymentMethod, type SplitMode } from "@receivy/common";
import { useEffect, useState } from "react";
import * as Crypto from "expo-crypto";
import { ActivityIndicator, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { FinancialRequestError, financialClient, type FinancialClient } from "@/financial/client";
import { peopleClient } from "@/people/client";

type Client = Pick<FinancialClient, "recurrences" | "paymentMethods" | "recurrenceProfile" | "saveRecurrence" | "transitionRecurrence">;
const stateLabel = { active: "Ativa", paused: "Pausada", ended: "Encerrada" };
function Button({ label, onPress, disabled = false }: { label: string; onPress: () => void; disabled?: boolean }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} className={`min-h-12 items-center justify-center rounded-xl border border-primary px-4 py-3 ${disabled ? "opacity-40" : "bg-surface"}`}><Text className="font-bold text-primary">{label}</Text></Pressable>;
}
export function RecurrencesScreen({ client = financialClient, people = peopleClient, onBack }: { client?: Client; people?: Pick<typeof peopleClient, "list">; onBack?: () => void }) {
  const [rules, setRules] = useState<RecurrenceDetail[]>([]); const [selected, setSelected] = useState<RecurrenceDetail | null>(null); const [editing, setEditing] = useState(false);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [confirm, setConfirm] = useState(false);
  async function load() { setLoading(true); setError(""); try { setRules((await client.recurrences()).recurrences); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { void client.recurrences().then(page => setRules(page.recurrences)).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [client]);
  function saved(rule: RecurrenceDetail) { setRules(old => [rule, ...old.filter(r => r.id !== rule.id)]); setSelected(rule); setEditing(false); }
  async function transition(action: "pause" | "reactivate" | "end") { if (!selected) return; setBusy(true); setError(""); try { saved(await client.transitionRecurrence(selected.id, action)); setConfirm(false); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (editing) return <RecurrenceEditor client={client} people={people} rule={selected} onSaved={saved} onBack={() => setEditing(false)} />;
  return <SafeAreaView className="flex-1 bg-canvas"><ScrollView contentContainerClassName="gap-5 p-5 pb-20"><Button label="Timeline" onPress={() => onBack?.()} /><Text className="text-4xl font-extrabold text-primary-strong">Recorrências</Text><Text className="text-muted">Regras futuras. Cobranças já criadas permanecem intactas.</Text><Button label="Nova recorrência" onPress={() => { setSelected(null); setEditing(true); }} />
    {loading && <ActivityIndicator accessibilityLabel="Carregando recorrências" />}{error ? <><Text accessibilityRole="alert" className="text-red-700">{error}</Text><Button label="Tentar novamente" onPress={() => void load()} /></> : null}
    {selected ? <><Button label="Todas as recorrências" onPress={() => { setSelected(null); setConfirm(false); }} /><Text className="text-3xl font-bold text-primary-strong">{selected.description}</Text><Text className="text-muted">{stateLabel[selected.state]} · {selected.frequency === "monthly" ? "Mensal" : "Anual"} · {selected.timezone}</Text><Text className="text-3xl font-extrabold text-ink">{formatMoney({ amountCents: selected.totalCents, currency: "BRL" })}</Text><Text>Próxima materialização: {selected.nextMaterialization ?? "Sem materialização prevista"}</Text>
      {selected.state !== "ended" && <><Button label="Editar" disabled={busy} onPress={() => setEditing(true)} /><Button label={selected.state === "active" ? "Pausar" : "Reativar"} disabled={busy} onPress={() => void transition(selected.state === "active" ? "pause" : "reactivate")} /><Button label="Encerrar" disabled={busy} onPress={() => setConfirm(true)} /></>}
      {confirm && <View className="gap-3 rounded-xl border border-outline p-4"><Text>Encerrar impede novas ocorrências e não cancela cobranças já criadas. Esta ação não pode ser desfeita.</Text><Button label="Confirmar encerramento" disabled={busy} onPress={() => void transition("end")} /><Button label="Voltar" onPress={() => setConfirm(false)} /></View>}
      <Text className="text-muted">Ao reativar, vencimentos anteriores à reativação não serão cobrados.</Text><Text className="text-2xl font-bold text-primary-strong">Simulação de 90 dias</Text><Text className="text-muted">Ainda não é cobrança. Projeções não entram no saldo e não permitem pagamento, comprovante ou link.</Text>{selected.previews.map(p => <View key={p.occurrenceDate} className="gap-2 border-l-2 border-primary pl-4 py-3"><Text className="font-bold text-primary">A receber · Previsto</Text><Text className="text-xl font-bold text-ink">{p.occurrenceDate} · {formatMoney(p.amount)}</Text><Text className="text-muted">Materialização em {p.materializationDate ?? p.occurrenceDate}</Text></View>)}{!selected.previews.length && <Text>Nenhuma ocorrência futura nesta janela.</Text>}</> : <>{!loading && !error && !rules.length && <Text>Nenhuma recorrência. Crie uma regra para acompanhar os próximos vencimentos.</Text>}{rules.map(rule => <View key={rule.id} className="gap-3 border-l-2 border-primary py-4 pl-4"><Text className="text-xl font-bold text-primary-strong">{rule.description}</Text><Text>{stateLabel[rule.state]} · {formatMoney({ amountCents: rule.totalCents, currency: "BRL" })}</Text><Button label={`Abrir ${rule.description}`} onPress={() => setSelected(rule)} /></View>)}</>}
  </ScrollView></SafeAreaView>;
}

function RecurrenceEditor({ client, people, rule, onSaved, onBack }: { client: Client; people: Pick<typeof peopleClient, "list">; rule: RecurrenceDetail | null; onSaved: (rule: RecurrenceDetail) => void; onBack: () => void }) {
  const [contacts, setContacts] = useState<Person[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [methods, setMethods] = useState<PaymentMethod[]>([]);
  const [selected, setSelected] = useState(rule?.split.parts.flatMap(p => p.kind === "person" ? [p.personId] : []) ?? []); const [owner, setOwner] = useState(rule ? rule.split.parts.some(p => p.kind === "owner") || rule.split.mode === "fixed" : true);
  const [amount, setAmount] = useState(rule ? formatMoney({ amountCents: rule.totalCents, currency: "BRL" }).replace(/[^\d,]/g, "") : ""); const [description, setDescription] = useState(rule?.description ?? "");
  const [frequency, setFrequency] = useState<"monthly" | "yearly">(rule?.frequency ?? "monthly"); const [day, setDay] = useState(String(rule?.day ?? new Date().getDate())); const [month, setMonth] = useState(String(rule?.month ?? 1));
  const [start, setStart] = useState(rule?.startDate ?? ""); const [end, setEnd] = useState(rule?.endDate ?? ""); const [timezone, setTimezone] = useState(rule?.timezone ?? "America/Sao_Paulo"); const [pix, setPix] = useState(rule?.paymentMethodId ?? "");
  const [mode, setMode] = useState<SplitMode>(rule?.split.mode ?? "equal"); const [values, setValues] = useState<Record<string, string>>(Object.fromEntries(rule?.split.parts.map(p => [p.kind === "owner" ? "owner" : p.personId, "amountCents" in p ? formatMoney({ amountCents: p.amountCents, currency: "BRL" }).replace(/[^\d,]/g, "") : "basisPoints" in p ? String(p.basisPoints / 100).replace(".", ",") : ""]) ?? []));
  const [reminders, setReminders] = useState(rule?.reminders ?? [-3, 0, 2].map(offsetDays => ({ offsetDays, channel: "auto" as const, enabled: true })));
  const [review, setReview] = useState<RecurrenceInput | null>(null); const [busy, setBusy] = useState(false); const [ready, setReady] = useState(false); const [error, setError] = useState(""); const [reload, setReload] = useState(0); const [attempt, setAttempt] = useState<{ input: RecurrenceInput; key: string; uncertain: boolean } | null>(null);
  async function loadMore(next?: string) { const page = await people.list(false, next); setContacts(old => [...old, ...page.people.filter(p => !old.some(a => a.id === p.id))]); setCursor(page.nextCursor); }
  useEffect(() => { void Promise.all([people.list(false).then(page => { setContacts(page.people); setCursor(page.nextCursor); }), client.paymentMethods().then(page => setMethods(page.paymentMethods)), rule ? Promise.resolve() : client.recurrenceProfile().then(({ user }) => { const today = calendarDate(new Date(), user.timezone); setTimezone(user.timezone); setStart(today); setDay(String(Number(today.slice(8)))); })]).then(() => setReady(true)).catch(e => setError(e.message)); }, [client, people, rule, reload]);
  const locked = !!attempt;
  function change(action: () => void) { if (!locked) { action(); setReview(null); } }
  function prepare() { setError(""); try { if (!selected.length) throw new Error("Selecione ao menos um contato."); const parties = [...selected.map(personId => ({ kind: "person" as const, personId })), ...(owner ? [{ kind: "owner" as const }] : [])];
    const split = mode === "equal" ? { mode, parts: parties } : mode === "fixed" ? { mode, parts: selected.map(personId => ({ kind: "person" as const, personId, amountCents: parseBRLCents(values[personId] ?? "") })) } : { mode, parts: parties.map(p => ({ ...p, basisPoints: parsePercentageBasisPoints(values[p.kind === "owner" ? "owner" : p.personId] ?? "") })) };
    setReview(normalizeRecurrenceInput({ description, totalCents: parseBRLCents(amount), frequency, day: Number(day), month: Number(month), startDate: start || undefined, endDate: end || undefined, timezone, paymentMethodId: pix || undefined, split, reminders }));
  } catch (e) { setReview(null); setError((e as Error).message); } }
  async function save(retry = attempt) { if (!review && !retry) return; const sent = retry ?? { input: review!, key: Crypto.randomUUID(), uncertain: false }; setAttempt(sent); setBusy(true); setError(""); try { onSaved(await client.saveRecurrence(sent.input, sent.key, rule?.id)); } catch (e) { const uncertain = sent.uncertain || !(e instanceof FinancialRequestError) || e.status >= 500; setAttempt(uncertain ? { ...sent, uncertain: true } : null); setError((e as Error).message); } finally { setBusy(false); } }
  function field(label: string, value: string, setter: (value: string) => void, numeric = false) { return <View className="gap-2"><Text className="font-semibold text-ink">{label}</Text><TextInput accessibilityLabel={label} editable={!locked && ready} value={value} onChangeText={v => change(() => setter(v))} inputMode={numeric ? "decimal" : "text"} className="min-h-12 rounded-xl border border-outline bg-surface px-3 text-ink" /></View>; }
  return <SafeAreaView className="flex-1 bg-canvas"><ScrollView keyboardShouldPersistTaps="handled" contentContainerClassName="gap-5 p-5 pb-20"><Button label="Voltar" disabled={locked} onPress={onBack} /><Text className="text-3xl font-extrabold text-primary-strong">{rule ? "Editar recorrência" : "Nova recorrência"}</Text><Text className="text-muted">Edições afetam apenas ocorrências ainda não materializadas.</Text>{!ready && !error && <ActivityIndicator accessibilityLabel="Carregando dados" />}{!ready && error && <Button label="Tentar carregar novamente" onPress={() => { setError(""); setReload(n => n + 1); }} />}
    <Text className="text-2xl font-bold text-primary-strong">Pessoas e rateio</Text>{contacts.map(p => <Pressable accessibilityRole="checkbox" accessibilityLabel={p.name} accessibilityState={{ checked: selected.includes(p.id), disabled: locked || !ready }} disabled={locked || !ready} key={p.id} onPress={() => change(() => setSelected(old => old.includes(p.id) ? old.filter(id => id !== p.id) : [...old, p.id]))} className={`min-h-12 justify-center rounded-xl border p-3 ${selected.includes(p.id) ? "border-primary bg-primary-soft" : "border-outline bg-surface"}`}><Text>{p.name}</Text></Pressable>)}{cursor && <Button label="Carregar mais contatos" disabled={locked} onPress={() => void loadMore(cursor).catch(e => setError(e.message))} />}<Pressable accessibilityRole="checkbox" accessibilityLabel="Incluir minha parte" accessibilityState={{ checked: owner }} disabled={locked} onPress={() => change(() => setOwner(!owner))} className="min-h-12 justify-center"><Text>{owner ? "☑" : "☐"} Incluir minha parte</Text></Pressable>
    {field("Valor total", amount, setAmount, true)}{field("Descrição", description, setDescription)}<View className="flex-row flex-wrap gap-2">{(["equal", "fixed", "percentage"] as const).map((m, i) => <Button key={m} label={["Partes iguais", "Valores fixos", "Percentuais"][i]!} disabled={locked} onPress={() => change(() => setMode(m))} />)}</View><Text>Rateio: {mode === "equal" ? "Partes iguais" : mode === "fixed" ? "Valores fixos" : "Percentuais"}</Text>{mode !== "equal" && [...selected, ...(owner && mode === "percentage" ? ["owner"] : [])].map(id => <View key={id}>{field(`Rateio ${id === "owner" ? "Minha parte" : contacts.find(p => p.id === id)?.name ?? "Contato indisponível"}`, values[id] ?? "", v => setValues(old => ({ ...old, [id]: v })), true)}</View>)}
    <Text className="text-2xl font-bold text-primary-strong">Calendário e Pix</Text><View className="flex-row gap-3"><Button label="Mensal" disabled={locked} onPress={() => change(() => setFrequency("monthly"))} /><Button label="Anual" disabled={locked} onPress={() => change(() => setFrequency("yearly"))} /></View><Text>Frequência: {frequency === "monthly" ? "Mensal" : "Anual"}</Text>{field("Dia", day, setDay, true)}{frequency === "yearly" && field("Mês", month, setMonth, true)}<Text className="text-muted">Dias inexistentes usam o último dia do mês. Datas no formato AAAA-MM-DD.</Text>{field("Início", start, setStart)}{field("Fim opcional", end, setEnd)}{field("Fuso horário IANA", timezone, setTimezone)}<Text className="font-bold text-ink">Chave Pix usada nos links</Text><Button label="Usar chave principal, se houver" disabled={locked} onPress={() => change(() => setPix(""))} />{methods.map(p => <Button key={p.id} label={`${pix === p.id ? "✓ " : ""}${p.label || p.pixKey}`} disabled={locked} onPress={() => change(() => setPix(p.id))} />)}
    <Text className="text-2xl font-bold text-primary-strong">Lembretes</Text><Text className="text-muted">Canal automático: push disponível ou e-mail. Sem contato digital, compartilhe manualmente.</Text>{reminders.map((r, index) => <View className="gap-2" key={index}><Pressable accessibilityRole="checkbox" accessibilityLabel={`Lembrete ${index + 1}`} accessibilityState={{ checked: r.enabled }} disabled={locked} onPress={() => change(() => setReminders(old => old.map((v, i) => i === index ? { ...v, enabled: !v.enabled } : v)))} className="min-h-12 justify-center"><Text>{r.enabled ? "☑" : "☐"} Lembrete {index + 1}</Text></Pressable>{field(`Dias do lembrete ${index + 1}`, String(r.offsetDays), value => setReminders(old => old.map((v, i) => i === index ? { ...v, offsetDays: Number(value) } : v)), true)}</View>)}<Button label="Adicionar lembrete" disabled={locked || reminders.length >= 10} onPress={() => change(() => setReminders(old => [...old, { offsetDays: 0, channel: "auto", enabled: true }]))} /><Text className="text-muted">Sem lembrete habilitado, a cobrança é criada no vencimento.</Text>
    <Button label="Revisar recorrência" disabled={locked || !ready} onPress={prepare} />{review && <View className="gap-4 border-l-2 border-primary pl-4"><Text className="text-xl font-bold text-primary-strong">Revisão exata</Text>{resolveExpenseSplit(review.totalCents, 1, review.split).map(p => <Text key={p.kind === "owner" ? "owner" : p.personId}>{p.kind === "owner" ? "Minha parte" : contacts.find(a => a.id === p.personId)?.name}: {formatMoney({ amountCents: p.amountCents, currency: "BRL" })}</Text>)}<Button label="Salvar recorrência" disabled={busy || locked} onPress={() => void save(null)} /></View>}{busy && <ActivityIndicator accessibilityLabel="Salvando" />}{error ? <Text accessibilityRole="alert" className="text-red-700">{error}</Text> : null}{attempt?.uncertain && <Button label="Tentar salvar novamente" disabled={busy} onPress={() => void save()} />}
  </ScrollView></SafeAreaView>;
}
