"use client";

import { formatMoney, type ChargeDetail, type PublicLink } from "@receivy/common";
import { useCallback, useEffect, useState } from "react";
import { browserFetch } from "@/lib/auth/browser-fetch";
import { responseMessage } from "@/lib/financial-response";
import { ProofPanel } from "./proof-panel";
import { FirstSharePix } from "./first-share-pix";
import { NotificationPanel } from "./notification-panel";

export function ChargeDetailScreen({ id }: { id: string }) {
  const [charge, setCharge] = useState<ChargeDetail | null>(null); const [publicUrl, setPublicUrl] = useState("");
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await browserFetch(`/api/financial/charges/${id}`); if (!response.ok) throw new Error(await responseMessage(response, "Cobrança não encontrada.")); setCharge(await response.json()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível carregar a cobrança."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void browserFetch(`/api/financial/charges/${id}`).then(async response => {
    if (!response.ok) throw new Error(await responseMessage(response, "Cobrança não encontrada.")); return response.json() as Promise<ChargeDetail>;
  }).then(setCharge).catch(reason => setError(reason instanceof Error ? reason.message : "Não foi possível carregar a cobrança.")).finally(() => setLoading(false)); }, [id]);
  async function mutate(path: string, body?: object) { setBusy(true); setError(""); setNotice(""); try { const response = await browserFetch(`/api/financial/charges/${id}/${path}`, { method: "POST", ...(body ? { headers: { "content-type": "application/json" }, body: JSON.stringify(body) } : {}) }); if (!response.ok) throw new Error(await responseMessage(response, "Não foi possível atualizar a cobrança.")); setCharge(await response.json()); setNotice(path === "cancel" ? "Cobrança cancelada. Ela continuará no histórico." : "Pagamento integral registrado."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível atualizar a cobrança."); } finally { setBusy(false); } }
  async function link(action: "public-link" | "public-link/rotate", paymentMethodId?: string) { setBusy(true); setError(""); try { const response = await browserFetch(`/api/financial/charges/${id}/${action}`, { method: "POST", ...(paymentMethodId ? { headers: { "content-type": "application/json" }, body: JSON.stringify({ paymentMethodId }) } : {}) }); if (!response.ok) throw new Error(await responseMessage(response, "Não foi possível gerar o link.")); const result = await response.json() as PublicLink; setPublicUrl(`${window.location.origin}/pay/${encodeURIComponent(result.token)}`); if (paymentMethodId) await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível gerar o link."); } finally { setBusy(false); } }
  async function copy(value: string, success: string) { try { await navigator.clipboard.writeText(value); setNotice(success); setError(""); } catch { setError("Não foi possível copiar. Selecione o conteúdo e copie manualmente."); } }
  async function share() { if (!publicUrl) return; try { if (!navigator.share) return void copy(publicUrl, "Link copiado."); await navigator.share({ title: "Cobrança Receivy", url: publicUrl }); } catch (reason) { if ((reason as DOMException).name !== "AbortError") setError("Não foi possível abrir o compartilhamento. Copie o link manualmente."); } }
  if (loading) return <p role="status">Carregando cobrança…</p>;
  if (!charge) return <div>{error && <p role="alert" className="login-error">{error}</p>}<button onClick={() => void load()}>Tentar novamente</button></div>;
  const creditor = charge.direction === "receivable";
  return <section className="financial-page charge-detail"><header><span className={`direction-badge ${charge.direction}`}>{creditor ? "A receber" : "A pagar"}</span><h1>{charge.description}</h1><p>{charge.recipient.name} · vencimento {new Intl.DateTimeFormat("pt-BR", { dateStyle: "long", timeZone: "UTC" }).format(new Date(`${charge.dueDate}T00:00:00Z`))}</p></header>
    <div className="detail-ledger"><div><span>Valor</span><strong>{formatMoney(charge.amount)}</strong></div><div><span>Situação</span><strong>{charge.state === "pending" ? "Pendente" : charge.state === "paid" ? "Pago" : "Cancelado"}</strong></div></div>
    {charge.pix && <section className="detail-section"><h2>Pagamento por Pix</h2><p>{charge.state === "pending" ? "Confira o nome do destinatário no seu banco antes de transferir." : "Chave Pix registrada no histórico desta cobrança."}</p><div className="copy-field"><code>{charge.pix.key}</code><button type="button" onClick={() => void copy(charge.pix!.key, "Chave Pix copiada.")}>Copiar chave Pix</button></div></section>}
    {creditor && charge.state === "pending" && <section className="detail-section"><h2>Ações da cobrança</h2><div className="action-row"><button disabled={busy} className="primary-button" onClick={() => { if (window.confirm("Marcar como paga? Isso registra um pagamento integral e encerra a cobrança.")) void mutate("payments", { method: "pix" }); }}>Marcar como paga</button><button disabled={busy} className="danger-button" onClick={() => { if (window.confirm("Cancelar esta cobrança? Ela não poderá mais receber pagamento e continuará no histórico.")) void mutate("cancel"); }}>Cancelar cobrança</button></div>{charge.pix && <div className="action-row"><button disabled={busy} className="secondary-button" onClick={() => void link("public-link")}>Criar link</button>{publicUrl && <><button disabled={busy} className="secondary-button" onClick={() => void share()}>Compartilhar</button><button disabled={busy} className="secondary-button" onClick={() => void link("public-link/rotate")}>Trocar link</button></>}</div>}{publicUrl && <div className="copy-field"><code>{publicUrl}</code><button onClick={() => void copy(publicUrl, "Link copiado.")}>Copiar link</button></div>}</section>}
    {creditor && charge.sharingState === "pix_required" && <FirstSharePix busy={busy} publish={methodId => link("public-link", methodId)} />}
    {charge.sharingState === "legacy_without_pix" && <p>Esta cobrança foi publicada sem Pix. O histórico não pode ser alterado nem receber um novo link; combine o pagamento manualmente com o credor.</p>}
    {!creditor && <section className="detail-section"><h2>{charge.state === "pending" ? "Como pagar" : "Situação da cobrança"}</h2><p>{charge.state === "pending" ? charge.pix ? "Esta cobrança é somente leitura. Faça o Pix com a chave exibida e confirme os dados no seu banco." : "A chave Pix ainda não está disponível. Combine o pagamento com o credor." : charge.state === "paid" ? "Esta cobrança já foi paga. Nenhuma nova transferência é necessária." : "Esta cobrança foi cancelada e não deve ser paga."}</p></section>}
    <ProofPanel base={`/api/financial/charges/${id}/proofs`} state={charge.state} creditor={creditor} onChanged={() => void load()} />
    <NotificationPanel id={id} canRemind={creditor && charge.state === "pending" && !!charge.pix} />
    {error && <p role="alert" className="login-error">{error}</p>}{notice && <p role="status" className="success-notice">{notice}</p>}
  </section>;
}
