"use client";
import { calendarDate, formatMoney, normalizeRecurrenceInput, parseBRLCents, parsePercentageBasisPoints, resolveExpenseSplit,
  type RecurrenceDetail, type RecurrenceInput, type Person, type PaymentMethod, type SplitMode } from "@receivy/common";
import { useEffect, useState } from "react";
import { browserFetch } from "@/lib/auth/browser-fetch";
import { responseMessage } from "@/lib/financial-response";

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await browserFetch(path, init);
  if (!response.ok) { const error = new Error(await responseMessage(response, "Não foi possível salvar. Tente novamente.")); throw Object.assign(error, { status: response.status }); }
  return response.json() as Promise<T>;
}
const stateLabel = { active: "Ativa", paused: "Pausada", ended: "Encerrada" };
export function RecurrencesScreen() {
  const [rules, setRules] = useState<RecurrenceDetail[]>([]); const [selected, setSelected] = useState<RecurrenceDetail | null>(null);
  const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [confirm, setConfirm] = useState(false);
  async function load() { setLoading(true); setError(""); try { setRules((await request<{ recurrences: RecurrenceDetail[] }>("/api/financial/recurrences")).recurrences); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { void request<{ recurrences: RecurrenceDetail[] }>("/api/financial/recurrences").then(page => setRules(page.recurrences)).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []);
  function saved(rule: RecurrenceDetail) { setRules(old => [rule, ...old.filter(r => r.id !== rule.id)]); setSelected(rule); setEditing(false); }
  async function transition(action: "pause" | "reactivate" | "end") { if (!selected) return; setBusy(true); setError(""); try { saved(await request(`/api/financial/recurrences/${selected.id}/${action}`, { method: "POST" })); setConfirm(false); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (editing) return <RecurrenceEditor rule={selected} onSaved={saved} onBack={() => setEditing(false)} />;
  return <section className="financial-page"><header className="page-heading"><div><h1>Recorrências</h1><p>Regras futuras. Cobranças já criadas permanecem intactas.</p></div><button className="primary-button" onClick={() => { setSelected(null); setEditing(true); }}>Nova recorrência</button></header>
    {loading && <p role="status">Carregando recorrências…</p>}{error && <p role="alert" className="login-error">{error} <button onClick={() => void load()}>Tentar novamente</button></p>}
    {selected ? <><button className="secondary-button" onClick={() => { setSelected(null); setConfirm(false); }}>Todas as recorrências</button><h2>{selected.description}</h2><p>{stateLabel[selected.state]} · {selected.frequency === "monthly" ? "Mensal" : "Anual"} · {selected.timezone}</p><strong className="review-total">{formatMoney({ amountCents: selected.totalCents, currency: "BRL" })}</strong><p>Próxima materialização: {selected.nextMaterialization ?? "Sem materialização prevista"}</p>
      {selected.state !== "ended" && <div className="filter-strip"><button disabled={busy} onClick={() => setEditing(true)}>Editar</button><button disabled={busy} onClick={() => void transition(selected.state === "active" ? "pause" : "reactivate")}>{selected.state === "active" ? "Pausar" : "Reativar"}</button><button disabled={busy} onClick={() => setConfirm(true)}>Encerrar</button></div>}
      {confirm && <section role="alertdialog" aria-label="Encerrar recorrência"><p>Encerrar impede novas ocorrências e não cancela cobranças já criadas. Esta ação não pode ser desfeita.</p><button className="primary-button" disabled={busy} onClick={() => void transition("end")}>Confirmar encerramento</button><button className="secondary-button" onClick={() => setConfirm(false)}>Voltar</button></section>}
      <p>Pausar suspende novas cobranças. Ao reativar, vencimentos anteriores à reativação não serão cobrados.</p><h2>Simulação de 90 dias</h2><p>Ainda não é cobrança: projeções não entram no saldo e não permitem pagamento, comprovante ou link.</p><div className="timeline-list">{selected.previews.map(p => <article className="timeline-entry" key={p.occurrenceDate}><div className="timeline-dot" /><div><span className="direction-badge receivable">A receber · Previsto</span><h3>{p.occurrenceDate}</h3><p>Materialização em {p.materializationDate ?? p.occurrenceDate}</p></div><strong className="money">{formatMoney(p.amount)}</strong></article>)}</div>{!selected.previews.length && <p>Nenhuma ocorrência futura nesta janela.</p>}</> : <>{!loading && !error && !rules.length && <p>Nenhuma recorrência. Crie uma regra para acompanhar os próximos vencimentos.</p>}<div className="timeline-list">{rules.map(rule => <article className="timeline-entry" key={rule.id}><div className="timeline-dot" /><div className="timeline-entry-main"><h2>{rule.description}</h2><p>{stateLabel[rule.state]} · {rule.frequency === "monthly" ? "Mensal" : "Anual"}</p></div><strong className="money">{formatMoney({ amountCents: rule.totalCents, currency: "BRL" })}</strong><button className="secondary-button" aria-label={`Abrir ${rule.description}`} onClick={() => setSelected(rule)}>Abrir</button></article>)}</div></>}
  </section>;
}

function RecurrenceEditor({ rule, onSaved, onBack }: { rule: RecurrenceDetail | null; onSaved: (rule: RecurrenceDetail) => void; onBack: () => void }) {
  const [people, setPeople] = useState<Person[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [methods, setMethods] = useState<PaymentMethod[]>([]);
  const [selected, setSelected] = useState(rule?.split.parts.flatMap(p => p.kind === "person" ? [p.personId] : []) ?? []);
  const [owner, setOwner] = useState(rule ? rule.split.parts.some(p => p.kind === "owner") || rule.split.mode === "fixed" : true);
  const [amount, setAmount] = useState(rule ? formatMoney({ amountCents: rule.totalCents, currency: "BRL" }).replace(/[^\d,]/g, "") : "");
  const [description, setDescription] = useState(rule?.description ?? ""); const [frequency, setFrequency] = useState<"monthly" | "yearly">(rule?.frequency ?? "monthly");
  const [day, setDay] = useState(String(rule?.day ?? new Date().getDate())); const [month, setMonth] = useState(String(rule?.month ?? 1));
  const [start, setStart] = useState(rule?.startDate ?? ""); const [end, setEnd] = useState(rule?.endDate ?? ""); const [timezone, setTimezone] = useState(rule?.timezone ?? "America/Sao_Paulo"); const [pix, setPix] = useState(rule?.paymentMethodId ?? "");
  const [mode, setMode] = useState<SplitMode>(rule?.split.mode ?? "equal");
  const [values, setValues] = useState<Record<string, string>>(Object.fromEntries(rule?.split.parts.map(p => [p.kind === "owner" ? "owner" : p.personId, "amountCents" in p ? formatMoney({ amountCents: p.amountCents, currency: "BRL" }).replace(/[^\d,]/g, "") : "basisPoints" in p ? String(p.basisPoints / 100).replace(".", ",") : ""]) ?? []));
  const [reminders, setReminders] = useState(rule?.reminders ?? [-3, 0, 2].map(offsetDays => ({ offsetDays, enabled: true, channel: "auto" as const })));
  const [review, setReview] = useState<RecurrenceInput | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [ready, setReady] = useState(false); const [reload, setReload] = useState(0);
  const [attempt, setAttempt] = useState<{ input: RecurrenceInput; key: string; uncertain: boolean } | null>(null);
  async function loadMore(next?: string) { const page = await request<{ people: Person[]; nextCursor: string | null }>(`/api/people?archived=false${next ? `&cursor=${encodeURIComponent(next)}` : ""}`); setPeople(old => [...old, ...page.people.filter(p => !old.some(a => a.id === p.id))]); setCursor(page.nextCursor); }
  useEffect(() => { void Promise.all([request<{ people: Person[]; nextCursor: string | null }>("/api/people?archived=false").then(page => { setPeople(page.people); setCursor(page.nextCursor); }), request<{ paymentMethods: PaymentMethod[] }>("/api/financial/payment-methods").then(page => setMethods(page.paymentMethods)),
    rule ? Promise.resolve() : request<{ user: { timezone: string } }>("/api/auth/me").then(({ user }) => { const today = calendarDate(new Date(), user.timezone); setTimezone(user.timezone); setStart(today); setDay(String(Number(today.slice(8)))); })]).then(() => setReady(true)).catch(e => setError(e.message)); }, [rule, reload]);
  function prepare() { setError(""); try {
    if (!selected.length) throw new Error("Selecione ao menos um contato.");
    const parties = [...selected.map(personId => ({ kind: "person" as const, personId })), ...(owner ? [{ kind: "owner" as const }] : [])];
    const split = mode === "equal" ? { mode, parts: parties } : mode === "fixed" ? { mode, parts: selected.map(personId => ({ kind: "person" as const, personId, amountCents: parseBRLCents(values[personId] ?? "") })) } : { mode, parts: parties.map(p => ({ ...p, basisPoints: parsePercentageBasisPoints(values[p.kind === "owner" ? "owner" : p.personId] ?? "") })) };
    setReview(normalizeRecurrenceInput({ description, totalCents: parseBRLCents(amount), frequency, day: Number(day), month: Number(month), startDate: start || undefined, endDate: end || undefined, timezone, paymentMethodId: pix || undefined, split, reminders }));
  } catch (e) { setReview(null); setError((e as Error).message); } }
  async function save(retry = attempt) { if (!review && !retry) return; const sent = retry ?? { input: review!, key: crypto.randomUUID(), uncertain: false }; setAttempt(sent); setBusy(true); setError(""); try {
    const saved = await request<RecurrenceDetail>(`/api/financial/recurrences${rule ? `/${rule.id}` : ""}`, { method: rule ? "PATCH" : "POST", headers: { "content-type": "application/json", "idempotency-key": sent.key }, body: JSON.stringify(sent.input) }); onSaved(saved);
  } catch (e) { const status = (e as { status?: number }).status; const uncertain = sent.uncertain || !status || status >= 500; setAttempt(uncertain ? { ...sent, uncertain: true } : null); setError((e as Error).message); } finally { setBusy(false); } }
  const locked = !!attempt;
  const allocations = review ? resolveExpenseSplit(review.totalCents, 1, review.split) : [];
  return <section className="financial-page"><button className="secondary-button" disabled={locked} onClick={onBack}>Voltar</button><h1>{rule ? "Editar recorrência" : "Nova recorrência"}</h1><p>Edições afetam apenas ocorrências ainda não materializadas.</p>{!ready && !error && <p role="status">Carregando dados…</p>}{!ready && error && <button className="secondary-button" onClick={() => { setError(""); setReload(n => n + 1); }}>Tentar carregar novamente</button>}
    <div className="creation-layout"><form className="creation-form" onSubmit={e => { e.preventDefault(); prepare(); }} onChange={() => setReview(null)}><fieldset disabled={locked || !ready}><legend>Pessoas e rateio</legend><div className="person-picker">{people.map(p => <label key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={() => setSelected(old => old.includes(p.id) ? old.filter(id => id !== p.id) : [...old, p.id])} />{p.name}</label>)}</div>{cursor && <button type="button" onClick={() => void loadMore(cursor).catch(e => setError(e.message))}>Carregar mais contatos</button>}<label><input type="checkbox" checked={owner} onChange={e => setOwner(e.target.checked)} />Incluir minha parte</label>
      <label>Valor total<input aria-label="Valor total" inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} /></label><label>Descrição<input aria-label="Descrição" value={description} maxLength={500} onChange={e => setDescription(e.target.value)} /></label><label>Como dividir<select value={mode} onChange={e => setMode(e.target.value as SplitMode)}><option value="equal">Partes iguais</option><option value="fixed">Valores fixos</option><option value="percentage">Percentuais</option></select></label>
      {mode !== "equal" && [...selected, ...(owner && mode === "percentage" ? ["owner"] : [])].map(id => <label key={id}>{id === "owner" ? "Minha parte" : people.find(p => p.id === id)?.name ?? "Contato indisponível"}<input aria-label={`Rateio ${id === "owner" ? "Minha parte" : people.find(p => p.id === id)?.name}`} inputMode="decimal" value={values[id] ?? ""} onChange={e => setValues(old => ({ ...old, [id]: e.target.value }))} /></label>)}</fieldset>
      <fieldset disabled={locked || !ready}><legend>Calendário e Pix</legend><label>Frequência<select value={frequency} onChange={e => setFrequency(e.target.value as "monthly" | "yearly")}><option value="monthly">Mensal</option><option value="yearly">Anual</option></select></label><label>Dia<input type="number" min="1" max="31" value={day} onChange={e => setDay(e.target.value)} /></label>{frequency === "yearly" && <label>Mês<input type="number" min="1" max="12" value={month} onChange={e => setMonth(e.target.value)} /></label>}<p>Dias inexistentes usam o último dia do mês.</p><label>Início<input type="date" value={start} onChange={e => setStart(e.target.value)} /></label><label>Fim opcional<input type="date" value={end} onChange={e => setEnd(e.target.value)} /></label><label>Fuso horário IANA<input value={timezone} onChange={e => setTimezone(e.target.value)} /></label><label>Chave Pix usada nos links<select value={pix} onChange={e => setPix(e.target.value)}><option value="">Usar chave principal, se houver</option>{methods.map(p => <option key={p.id} value={p.id}>{p.label || p.pixKey}</option>)}</select></label></fieldset>
      <fieldset disabled={locked || !ready}><legend>Lembretes</legend><p>Canal automático: push disponível ou e-mail. Sem contato digital, compartilhe manualmente.</p>{reminders.map((r, index) => <div key={index}><label><input type="checkbox" checked={r.enabled} onChange={e => setReminders(old => old.map((a, i) => i === index ? { ...a, enabled: e.target.checked } : a))} />Lembrete {index + 1}</label><label>Dias em relação ao vencimento<input type="number" min="-90" max="90" value={r.offsetDays} onChange={e => setReminders(old => old.map((a, i) => i === index ? { ...a, offsetDays: Number(e.target.value) } : a))} /></label></div>)}<button type="button" disabled={reminders.length >= 10} onClick={() => setReminders(old => [...old, { offsetDays: 0, channel: "auto", enabled: true }])}>Adicionar lembrete</button><p>Sem lembrete habilitado, a cobrança é criada no vencimento.</p></fieldset><button className="primary-button" disabled={locked || !ready}>Revisar recorrência</button></form>
      <aside className="review-panel"><h2>Revisão exata</h2>{review && <><strong className="review-total">{formatMoney({ amountCents: review.totalCents, currency: "BRL" })}</strong><ul>{allocations.map(p => <li key={p.kind === "owner" ? "owner" : p.personId}>{p.kind === "owner" ? "Minha parte" : people.find(a => a.id === p.personId)?.name}: {formatMoney({ amountCents: p.amountCents, currency: "BRL" })}</li>)}</ul><button className="primary-button" disabled={busy || locked} onClick={() => void save(null)}>Salvar recorrência</button></>}{busy && <p role="status">Salvando…</p>}{error && <p className="login-error" role="alert">{error}</p>}{attempt?.uncertain && <button className="secondary-button" disabled={busy} onClick={() => void save()}>Tentar salvar novamente</button>}</aside></div>
  </section>;
}
