/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ProtectedRouteImport } from "./routes/_protected";
import { Route as OnboardingRouteImport } from "./routes/onboarding";
import { Route as ProtectedIndexRouteImport } from "./routes/_protected/index";
import { Route as ProtectedFeedRouteImport } from "./routes/_protected/feed";
import { Route as LoginIndexRouteImport } from "./routes/login/index";
import { Route as LoginCodeRouteImport } from "./routes/login/code";
import { Route as AuthOauthCallbackRouteImport } from "./routes/auth/oauth/callback";

const ProtectedRoute = ProtectedRouteImport.update({
  id: "/_protected",
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedFeedRoute = ProtectedFeedRouteImport.update({
  id: "/feed",
  path: "/feed",
  getParentRoute: () => ProtectedRoute,
} as any);
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: "/login/",
  path: "/login/",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginCodeRoute = LoginCodeRouteImport.update({
  id: "/login/code",
  path: "/login/code",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthOauthCallbackRoute = AuthOauthCallbackRouteImport.update({
  id: "/auth/oauth/callback",
  path: "/auth/oauth/callback",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof ProtectedIndexRoute;
  "/onboarding": typeof OnboardingRoute;
  "/feed": typeof ProtectedFeedRoute;
  "/login/code": typeof LoginCodeRoute;
  "/login/": typeof LoginIndexRoute;
  "/auth/oauth/callback": typeof AuthOauthCallbackRoute;
}
export interface FileRoutesByTo {
  "/onboarding": typeof OnboardingRoute;
  "/feed": typeof ProtectedFeedRoute;
  "/login/code": typeof LoginCodeRoute;
  "/": typeof ProtectedIndexRoute;
  "/login": typeof LoginIndexRoute;
  "/auth/oauth/callback": typeof AuthOauthCallbackRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_protected": typeof ProtectedRouteWithChildren;
  "/onboarding": typeof OnboardingRoute;
  "/_protected/feed": typeof ProtectedFeedRoute;
  "/login/code": typeof LoginCodeRoute;
  "/_protected/": typeof ProtectedIndexRoute;
  "/login/": typeof LoginIndexRoute;
  "/auth/oauth/callback": typeof AuthOauthCallbackRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/onboarding"
    | "/feed"
    | "/login/code"
    | "/login/"
    | "/auth/oauth/callback";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/onboarding"
    | "/feed"
    | "/login/code"
    | "/"
    | "/login"
    | "/auth/oauth/callback";
  id:
    | "__root__"
    | "/_protected"
    | "/onboarding"
    | "/_protected/feed"
    | "/login/code"
    | "/_protected/"
    | "/login/"
    | "/auth/oauth/callback";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren;
  OnboardingRoute: typeof OnboardingRoute;
  LoginCodeRoute: typeof LoginCodeRoute;
  LoginIndexRoute: typeof LoginIndexRoute;
  AuthOauthCallbackRoute: typeof AuthOauthCallbackRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_protected": {
      id: "/_protected";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_protected/": {
      id: "/_protected/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof ProtectedIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/feed": {
      id: "/_protected/feed";
      path: "/feed";
      fullPath: "/feed";
      preLoaderRoute: typeof ProtectedFeedRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/login/": {
      id: "/login/";
      path: "/login";
      fullPath: "/login/";
      preLoaderRoute: typeof LoginIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login/code": {
      id: "/login/code";
      path: "/login/code";
      fullPath: "/login/code";
      preLoaderRoute: typeof LoginCodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/oauth/callback": {
      id: "/auth/oauth/callback";
      path: "/auth/oauth/callback";
      fullPath: "/auth/oauth/callback";
      preLoaderRoute: typeof AuthOauthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface ProtectedRouteChildren {
  ProtectedFeedRoute: typeof ProtectedFeedRoute;
  ProtectedIndexRoute: typeof ProtectedIndexRoute;
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedFeedRoute: ProtectedFeedRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
};

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  LoginCodeRoute: LoginCodeRoute,
  LoginIndexRoute: LoginIndexRoute,
  AuthOauthCallbackRoute: AuthOauthCallbackRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
